stages:
    - test
    - build

before_script:
    - export PATH=$PATH:$GOROOT/bin

test:
    type: test
    script:
        - go test ./go/...
    tags:
        - docker

build:
    script:
        - go build ./go/...
    artifacts:
        paths:
            - app.exe
        expire_in: 1 week

