variables:
    - PATH=$PATH:$GOROOT/bin
    
    stages:
    - test
    - build
test:
    type: test
    script:
        - export PATH=$PATH:$GOROOT/bin
        - go test ./go/...
    tags:
        - docker

build:
    script:
        - go build ./go/...
    artifacts:
        paths:
            - app.exe
        expire_in: 1 week

