stages:
    - test

test_job:
    type: test
    script:
        - echo PATH=$PATH
        - export PATH=$PATH:$GOROOT/bin
        - echo PATH=$PATH
        - go test ./go/.
    tags:
        - docker
